# Generated by Django 5.1.1 on 2024-09-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tution', '0002_tution_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tution',
            name='category',
        ),
    ]
