# Generated by Django 5.1.1 on 2024-09-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tution', '0003_remove_tution_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tution',
            name='author',
        ),
    ]
