# Generated by Django 5.1.1 on 2024-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassCtg', '0001_initial'),
        ('Tution', '0004_remove_tution_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tution',
            name='category',
            field=models.ManyToManyField(to='ClassCtg.category'),
        ),
    ]
